### ISSUE TITLE
Error came up when running tests

### ISSUE THREAD

**Issue by wangyehhh** [wangyehhh/SpatialKappa#1]
The command stuck at test_addTransition (SpatialKappa.tests.TestSpatialKappa) ...

(Kappa37) C:\study\FinalProject\SpatialKappa\python>python setup.py test
Warning: 'classifiers' should be a list, got type 'tuple'
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing SpatialKappa.egg-info\PKG-INFO
writing dependency_links to SpatialKappa.egg-info\dependency_links.txt
writing requirements to SpatialKappa.egg-info\requires.txt
writing top-level names to SpatialKappa.egg-info\top_level.txt
reading manifest file 'SpatialKappa.egg-info\SOURCES.txt'
writing manifest file 'SpatialKappa.egg-info\SOURCES.txt'
running build_ext
test_addAgent (SpatialKappa.tests.TestSpatialKappa) ... ERROR
test_addTransition (SpatialKappa.tests.TestSpatialKappa) ...

Pycharm reported an ERROR when running test_addAgent(SpatialKappa.tests.TestSpatialKappa) as below:
Traceback (most recent call last):
  File "C:\study\anaconda\envs\Kappa37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\study\anaconda\envs\Kappa37\lib\unittest\case.py", line 611, in run
    self.setUp()
  File "C:\study\FinalProject\SpatialKappa\python\SpatialKappa\tests\__init__.py", line 11, in setUp
    self.sim = self.sk.kappa_sim("ms", True)
  File "C:\study\anaconda\envs\Kappa37\lib\site-packages\spatialkappa-2.1.5-py3.7.egg\SpatialKappa\__init__.py", line 145, in kappa_sim
    ks = self.gateway.jvm.org.demonsoft.spatialkappa.api.SpatialKappaSim(time_units, verbose, seed)
TypeError: 'JavaPackage' object is not callable

**Comment by davidcsterratt** [comment]
Hmmm... it looks like py4j has not created the connection to the Java object properly. I suggest trying the following code:
```
import SptialKappa

sk = SpatialKappa()
```
Assuming there are no errors, examine the values of
`sk.port`, `sk.gateway_client` and `sk.gateway` . 

I am wondering if the py4j interface may have changed. The documentation here may be helpful:
https://www.py4j.org/py4j_java_gateway.html
